// races.js
// On crée un "namespace" global unique pour toutes les données du jeu.
var EcoSimData = window.EcoSimData || {};

EcoSimData.racesData = {
  "races": {
    "Humain": {
      "prenomsM": ["Gareth", "Ivor", "Alistair", "Roland", "Cedric", "Edric", "Tristan", "Lucian", "Frederic", "Bastian", "Hugh", "Victor", "Landon", "Marcus", "Emery", "Theodore", "Benedict", "Gregory", "Nathaniel", "Sebastian", "Julian", "Dominic", "Maximilian", "Alexander", "William", "Benjamin", "Christopher", "Nicholas", "Jonathan", "Samuel", "Daniel", "Matthew", "Anthony", "Henry", "Charles"],
      "prenomsF": ["Rowena", "Maribel", "Aveline", "Isolde", "Eleanor", "Viviane", "Selene", "Clarisse", "Juliette", "Helena", "Rosaline", "Beatrix", "Camille", "Emilia", "Daphne", "Genevieve", "Josephine", "Margaret", "Charlotte", "Victoria", "Elizabeth", "Catherine", "Anastasia", "Isabella", "Sophia", "Olivia", "Amelia", "Abigail", "Evelyn", "Harriet", "Penelope", "Arabella", "Seraphina", "Lillian", "Adelaide"],
      "noms": ["Vaelis", "Blackthorn", "Ashford", "Stormwind", "Ironwood", "Ravencrest", "Everhart", "Lockwood", "Gravesend", "Montclair", "Redwyne", "Fairchild", "Carrington", "Winchester", "Hawthorne", "Kingsley", "Worthington", "Hargrave", "Ellington", "Prescott", "Harrington", "Whitmore", "Blackwood", "Stirling", "Waverly", "Langley", "Thornton", "Clifton", "Radcliffe", "Winslow", "Ellsworth", "Blackwell", "Kensington", "Wexford", "Ashworth","Valerian", "Silverlake", "Dunewood", "Stonewall", "Stormrider", "Evermore", "Winterbourne", "Ravenmoor", "Brighthart", "Rivermoor", "Blackmoor", "Griffincrest", "Ashbourne", "Redford", "Fairburn", "Kingswell", "Goldleaf", "Lionsgate", "Brightwood", "Lockheart", "Stonemoor", "Windrider", "Frosthelm", "Emberstone", "Mooncrest", "Falken", "Montfort", "Blackswan", "Nightriver", "Rosedale", "Steinwald", "Torvald", "Mournblade", "Falkwood", "Grayson", "Castellano", "Marwood", "Duskwood", "Sablehart", "Luminara", "Dantech", "Roselock", "Drakestone", "Suncrest", "Verdant", "Lionheart", "Frostwind", "Thornfield", "Griffonhall", "Ebonhart", "Arden", "Briarwood", "Morningside", "Oakenshield", "Vermont", "Aldercroft", "Graystone", "Belmont", "Caldera", "Rosetti", "Montverde", "Valdoro", "Rivermount", "Corvinus", "Alvarado", "Rinaldi", "Belladonna", "Stellaire", "Castiglione", "Ferraros", "Caravelle", "Donatello", "Marinelli", "Guillemard", "Lacroix", "Verducci", "Montgomery", "Bellforte", "Solis", "Fortunato", "Montalban", "Santoro", "Rosabella", "Delacroix", "Roccabella", "Bellavita", "Ventura", "Rosano", "Cervantes", "Montesque", "Draconis", "Valenti", "Castigliani", "Marcellus", "Lombardi", "Giovanni", "Ravenhart", "Blackspire", "Ebonwood", "Gallowmere"],
      "ageAdulte": 18,
      "esperanceVieMax": 80,
      "dureeGestationMois": 9,
      "ageApprentissage": 4,
      "ageTravail": 14
    },
    "Elfe": {
      "prenomsM": ["Eldrin", "Lorien", "Aerendyl", "Thalion", "Faelar", "Caerthian", "Vaerion", "Sylvaris", "Ithilion", "Orendil", "Caladhel", "Eryndor", "Fenian", "Melarion", "Iltharion", "Galadrion", "Celeborn", "Thranduil", "Elrond", "Legolas", "Haldir", "Glorfindel", "Celebrimbor", "Amroth", "Cirdan", "Ecthelion", "Finrod", "Gildor", "Imrahil", "Mithrandir", "Orophin", "Rumil", "Saeros", "Turgon", "Vorondil"],
      "prenomsF": ["Aeloria", "Sylvara", "Aerith", "Luthien", "Galadriel", "Elenwen", "Isilme", "Naeriel", "Althaea", "Vaerina", "Lyari", "Eldalisse", "Mythrelle", "Yavanna", "Anariel", "Arwen", "Celebrian", "Idril", "Nimrodel", "Aredhel", "Finduilas", "Melian", "Nessa", "Varda", "Yavanna", "Vaire", "Nienna", "Estë", "Vána", "Ilmarë", "Uinen", "Arien", "Tilion", "Eärwen", "Indis"],
      "noms": ["Moonblade", "Starwind", "Dawnwhisper", "Nightbreeze", "Silverleaf", "Evenwood", "Sunshadow", "Ravensong", "Featherstone", "Elderglade", "Skywhisper", "Moonbrook", "Windrider", "Starbloom", "Brightbranch", "Evenstar", "Lothlórien", "Imladris", "Mithlond", "Caras Galadhon", "Tirion", "Alqualondë", "Formenos", "Gondolin", "Nargothrond", "Menegroth", "Doriath", "Himring", "Amon Lanc", "Eregion", "Lindon", "Eldamar", "Valinor", "Aman", "Tol Eressëa", "Silversong", "Moonwhisper", "Duskleaf", "Starglade", "Dawnlily", "Elenaril", "Faywind", "Starbreeze", "Aurorasil", "Elensong", "Sylvanbloom", "Lunawind", "Aurawhisper", "Glimmerbranch", "Celestine", "Moonshimmer", "Starfrost", "Duskweaver", "Silverstream", "Lunaris", "Mistdancer", "Skyfrost", "Auroraflame", "Dawnshadow", "Silvershade", "Windglimmer", "Stellaflame", "Nightfall", "Elunara", "Moonpetal", "Starflower", "Evenlight", "Luminora", "Sundrop", "Stardew", "Moonlight", "Eternis", "Celestwind", "Auroravine", "Moonmist", "Lunarion", "Starflow", "Twilight", "Elvensong", "Duskpetal", "Skyshine", "Starveil", "Celestia", "Moonbrook", "Dawnfall", "Evenbloom", "Silverbreeze", "Starlace", "Glimmershadow", "Moonbloom", "Duskveil", "Sunlily", "Elinor", "Aurorae", "Dawnleaf", "Moonlace", "Starwhisper", "Glimmerleaf", "Twilightsong", "Elensil", "Mooncrest", "Stardancer", "Celestbranch", "Aurorafrost", "Duskwing", "Evenbreeze", "Silverveil", "Starbrook", "Moonflame", "Dawnbloom", "Celestglow", "Everbloom", "Lunarlight", "Starfire", "Moonstream", "Duskshine", "Evenwind", "Silverdusk", "Celestial", "Aurorablossom", "Starweaver", "Moonlance", "Dawnwind", "Elvenbloom", "Skystar", "Lunaria", "Duskwhisper", "Moonshadow", "Auroralight", "Starglow", "Celestbreeze", "Evenmist", "Moonvale", "Starhaven", "Dawnstar"],
      "ageAdulte": 20,
      "esperanceVieMax": 750,
      "dureeGestationMois": 18,
      "ageApprentissage": 4,
      "ageTravail": 18
    },
    "Demi-Elfe": {
      "prenomsM": ["Caelum", "Theron", "Aelric", "Eldric", "Lorand", "Vaelin", "Sylric", "Malwen", "Tyrel", "Darian", "Kaelor", "Oryn", "Lirion", "Fenric", "Calion", "Erevan", "Faolan", "Gaelin", "Halasían", "Ithron", "Jhaer", "Kaelar", "Lorcan", "Mithron", "Nael", "Orion", "Paelion", "Quarion", "Rolen", "Sael", "Talion", "Urien", "Vaelan", "Wyn", "Xanion", "Yllan"],
      "prenomsF": ["Liora", "Elysia", "Aelara", "Sylvana", "Ariella", "Seraphina", "Elora", "Myrielle", "Vaessa", "Naeris", "Thalindra", "Alannis", "Isendre", "Mirelle", "Talyndra", "Aelindra", "Briareth", "Caelith", "Dirae", "Eilistraee", "Faelindra", "Gaelira", "Halisstra", "Ilyana", "Jhaelryna", "Kethryllia", "Liriel", "Miraal", "Nuala", "Orianna", "Phaeralla", "Qilué", "Rhyll", "Sariel", "Taenya", "Urmelena"],
      "noms": ["Dawnbringer", "Silversong", "Amberwind", "Moonshadow", "Starflower", "Brightvale", "Evermoon", "Ravenhart", "Stormgale", "Frostbloom", "Hallowglen", "Sunvale", "Shadowbrook", "Willowmere", "Embercrest", "Halfmoon", "Evenfall", "Duskwhisper", "Starlight", "Moonhollow", "Sunflare", "Dawnspire", "Nightshade", "Mistvale", "Cloudcrest", "Rainwhisper", "Stormspire", "Frostwind", "Wintergale", "Autumnleaf", "Springbloom", "Summerglen", "Thundershade", "Lightbreeze", "Darkpetal", "Aurorabringer", "Silverbloom", "Moonglade", "Duskveil", "Sunwhisper", "Starbrook", "Evenflame", "Frostvale", "Shadowglen", "Emberwind", "Celestbloom", "Mistgale", "Nightbloom", "Dawnmist", "Cloudflare", "Stormlily", "Mooncrest", "Sunshard", "Starhollow", "Evenbrook", "Duskpetal", "Lightgale", "Frostbreeze", "Emberglow", "Twilightvale", "Moonflare", "Sunshadow", "Starwhisper", "Dawnpetal", "Evenstar", "Mistveil", "Nightgale", "Cloudwhisper", "Stormshard", "Auroravale", "Silverbreeze", "Moonlily", "Duskbrook", "Sunflare", "Starshard", "Evenfall", "Frostwhisper", "Emberdusk", "Celestwind", "Twilightglow", "Moonshimmer", "Dawnshadow", "Nightspire", "Cloudglen", "Stormwhisper", "Aurorashade", "Silverflare", "Moonbeam", "Duskdancer", "Sunlily", "Starveil", "Evenbloom", "Mistshard", "Nightbreeze", "Cloudspire", "Stormdusk", "Auroraflame", "Silvershade", "Moonwisp", "Dawncrest", "Sunbrook", "Starstream", "Evenlight", "Frostdawn", "Emberfrost", "Celestbreeze", "Twilightshard", "Moonember", "Dawnbrook", "Sunpetal", "Starflame", "Evenmist", "Mistbrook", "Nightflame", "Cloudbloom", "Stormlark", "Aurorawind", "Silvermist", "Moonspire", "Duskwing", "Sunbeam", "Starflare", "Evenhollow", "Frostbrook", "Emberstorm", "Celestpetal", "Twilightwing", "Moonrise", "Dawnwing", "Sunshimmer", "Stardancer", "Evenhaze", "Mistgleam", "Nightshard", "Cloudlily"],
      "ageAdulte": 19,
      "esperanceVieMax": 180,
      "dureeGestationMois": 12,
      "ageApprentissage": 4,
      "ageTravail": 16
    },
    "Orc": {
      "prenomsM": ["Gorruk", "Tharok", "Borgakh", "Gruk", "Morgul", "Urgash", "Zogmar", "Drogath", "Vorgak", "Hraknor", "Zarnok", "Torug", "Kazgar", "Urdan", "Skarn", "Azog", "Bolgr", "Dugrul", "Fargash", "Ghash", "Hogar", "Jorg", "Korgul", "Lugdush", "Mauhúr", "Narg", "Ogrash", "Pug", "Rugdush", "Shagrat", "Tugog", "Uglúk", "Vrask", "Wugrash", "Yazneg"],
      "prenomsF": ["Graga", "Morga", "Bagra", "Urga", "Sharga", "Vorka", "Zugra", "Drakka", "Krasha", "Zulga", "Ogra", "Krota", "Braga", "Thurka", "Narza", "Azog", "Bolg", "Durbag", "Ghash", "Hug", "Jarga", "Kraka", "Lugburz", "Mazog", "Narg", "Ogrash", "Pug", "Ragash", "Shagga", "Tugog", "Ugbash", "Vorga", "Wug", "Yazga", "Zogga"],
      "noms": ["Ironjaw", "Bloodfist", "Bonecrusher", "Skullsplitter", "Warbringer", "Blackfang", "Doomhammer", "Stormscar", "Ironhide", "Thundermaw", "Battleborn", "Steelclaw", "Ragefang", "Blightclaw", "Darkmaul", "Gorefang", "Deathmaw", "Rustblade", "Grimskull", "Hatecleaver", "Mangletooth", "Rotgut", "Slagheart", "Terrorgrip", "Vileblade", "Warpike", "Xal'gor", "Yak'gor", "Zog'nar", "Azkor", "Brak'thar", "Crag'gor", "Drog'ath", "Ekk'zar", "Frak'gar", "Ironfang", "Bloodmaw", "Bonegnasher", "Skullcrusher", "Warhowl", "Blacktooth", "Doomfist", "Stormcleaver", "Ironfist", "Thunderfang", "Battleaxe", "Steelmaw", "Rageclaw", "Blightfang", "Darkhowl", "Goremaw", "Deathclaw", "Rustfang", "Grimblood", "Hatemaul", "Manglejaw", "Rotfang", "Slagfist", "Terrorhowl", "Vilemaw", "Warscar", "Bloodcleaver", "Brutemaul", "Venomblood", "Ashfang", "Wargrin", "Dreadfang", "Ironrage", "Furyfist", "Gutripper", "Crimsonhowl", "Doomscar", "Wargheart", "Rageborn", "Rotspike", "Daggerfang", "Hollowtooth", "Shatterfist", "Blazemaul", "Thunderclaw", "Nightfang", "Stormfang", "Ironspike", "Venomjaw", "Dreadclaw", "Battlefang", "Brutetooth", "Fleshrender", "Ironmaul", "Blightfury", "Darkscar", "Shadowcleaver", "Warcrusher", "Tuskbreaker", "Firefang", "Voidclaw", "Dreadjaw", "Gorebreaker", "Rotmaw", "Wargclaw", "Skullhowl", "Hatejaw", "Bloodfang", "Ironmaw", "Frostfang", "Ragecrusher", "Savagehowl", "Venomscar", "Stormbreaker", "Warfang", "Ashmaw", "Hollowfang", "Flamecleaver", "Furyfang", "Vortexfang", "Dreadmaw", "Voidfang", "Terrorfang", "Hellscar", "Steelbreaker", "Ragehowl", "Goreclaw", "Daggermaw", "Cragfang", "Brutefist", "Shadowfang", "Gutripper", "Darkfang", "Skullmaw", "Blightclaw", "Rotbreaker", "Havocfang", "Fireclaw", "Stormcrusher", "Wrathfang", "Ironhowl", "Nightmaw", "Voidmaul"],
      "ageAdulte": 11,
      "esperanceVieMax": 60,
      "dureeGestationMois": 6,
      "ageApprentissage": 3,
      "ageTravail": 8
    },
    "Demi-Orc": {
      "prenomsM": ["Gorran", "Tharon", "Borgan", "Grukan", "Morgar", "Urkan", "Zogran", "Drogmar", "Varkan", "Hrok", "Zarnak", "Torun", "Kazrik", "Urdak", "Skor", "Azhak", "Borkul", "Drokk", "Gorzak", "Hrogar", "Jorgal", "Krogar", "Lugak", "Morgak", "Narok", "Orghar", "Porg", "Rogar", "Shagar", "Torgak", "Ugor", "Vorgak", "Wrogar", "Xorg", "Yorg"],
      "prenomsF": ["Gara", "Mara", "Bara", "Urana", "Shara", "Vora", "Zura", "Draga", "Kraga", "Zura", "Ogra", "Kara", "Braka", "Thura", "Narga", "Agra", "Borga", "Droga", "Gorza", "Hroga", "Jorga", "Kroga", "Lugra", "Morza", "Nagra", "Orga", "Pogra", "Rogra", "Shagra", "Togra", "Ugra", "Vorga", "Wroga", "Xogra", "Yogra"],
      "noms": ["Steeljaw", "Redfist", "Stonebreaker", "Ironhide", "Bloodaxe", "Stormcrusher", "Darkfang", "Shadowmaw", "Ragehammer", "Doomscar", "Thunderjaw", "Grimclaw", "Warchild", "Firebrand", "Frostfang", "Gorehowl", "Deathgrip", "Rustfang", "Grimblade", "Hatecleaver", "Mangler", "Rotfang", "Slagmaw", "Terrorfang", "Viletooth", "Warsong", "Xal'gur", "Yak'mar", "Zog'gar", "Azkar", "Brak'dar", "Crag'mar", "Drog'ash", "Ekk'zor", "Frak'mar", "Steelmaw", "Redclaw", "Stonefang", "Ironfury", "Bloodhowl", "Stormmaul", "Darkscar", "Shadowfang", "Rageclaw", "Doomjaw", "Thunderclaw", "Grimfang", "Warborn", "Firestrike", "Frostmaw", "Gorecleaver", "Deathfang", "Rustjaw", "Grimfist", "Hatetooth", "Manglefang", "Rotmaw", "Slagclaw", "Terrormaw", "Viletusk", "Warhowl", "Stormtusk", "Ironbrand", "Cragfist", "Daggerfang", "Bruteborn", "Dreadscar", "Venomclaw", "Ashfury", "Wargborn", "Hollowfang", "Furyjaw", "Blazefang", "Nightscar", "Shadowcleaver", "Ragestrike", "Doomcleaver", "Firefang", "Voidclaw", "Terrorjaw", "Hellfang", "Steelborn", "Rageheart", "Thunderborn", "Warchild", "Savagefang", "Stormfang", "Darkcleaver", "Battlejaw", "Crimsonfang", "Flamejaw", "Ironscar", "Bloodbrand", "Stormrider", "Warbringer", "Frostborn", "Blightfang", "Daggerjaw", "Goremaul", "Venomtusk", "Wrathfang", "Tuskbreaker", "Rageshade", "Gutripper", "Cragborn", "Shadowjaw", "Fireclaw", "Havocfang", "Blazemaul", "Vortexfang", "Dreadjaw", "Voidfang", "Ashfang", "Thunderstrike", "Stormcrusher", "Blackfang", "Ironhowl", "Rotclaw", "Battleborn", "Savageshade", "Grimjaw", "Skullfang", "Bloodscar", "Darkhowl", "Stonejaw", "Slagtusk", "Warspike", "Stormhowl", "Frostclaw", "Daggerstrike", "Doomfang", "Ironbreaker", "Crimsonclaw", "Thundershade", "Rageborn", "Grimblood", "Dreadscar", "Warshade", "Nightfang"],
      "ageAdulte": 12,
      "esperanceVieMax": 70,
      "dureeGestationMois": 8,
      "ageApprentissage": 3,
      "ageTravail": 10
    },
    "Nain": {
      "prenomsM": ["Thorin", "Balin", "Dain", "Gimli", "Durin", "Brom", "Haldar", "Gorrim", "Krag", "Varrik", "Thrain", "Gundar", "Mordin", "Storn", "Torbjorn", "Fili", "Kili", "Oin", "Gloin", "Bifur", "Bofur", "Bombur", "Dwalin", "Ori", "Nori", "Dori", "Frar", "Loni", "Nali", "Thror", "Fundin", "Gróin", "Flói", "Frár", "Kíli"],
      "prenomsF": ["Disa", "Frida", "Gerd", "Helga", "Ingrid", "Sif", "Astrid", "Brynja", "Hilda", "Yrsa", "Torhild", "Gudrun", "Ragna", "Eira", "Vigdis", "Dagmar", "Elin", "Freydis", "Gerda", "Hervor", "Idunn", "Jorunn", "Kára", "Lif", "Mist", "Nanna", "Oddny", "Rannveig", "Sigrun", "Thordis", "Ulfhild", "Védis", "Yngvild", "Åse", "Ölrun"],
      "noms": ["Ironhelm", "Stonefoot", "Amberaxe", "Goldbeard", "Hammerfist", "Deepdelver", "Flamebeard", "Frostmantle", "Battlehammer", "Stronghold", "Thunderforge", "Runeblade", "Gravelfist", "Stormdelver", "Rockshield", "Anvilmar", "Bronzebeard", "Copperpick", "Darkiron", "Everpeak", "Fireforge", "Granitegrip", "Hearthhome", "Ironshield", "Jadehammer", "Kegbreaker", "Longbeard", "Mithrilhand", "Noblepeak", "Oakenfist", "Proudspire", "Quakefist", "Rubyeye", "Steelheart", "Trueforge", "Ironfist", "Stonehammer", "Goldmantle", "Amberbeard", "Steelgrip", "Thunderbraid", "Stormshield", "Battlefury", "Frostforge", "Anvilfist", "Deepstone", "Boulderhelm", "Rockbraid", "Graniteshield", "Runebeard", "Mithrilaxe", "Firebraid", "Oakenforge", "Darkmantle", "Stormbreaker", "Ironclad", "Strongfist", "Copperhelm", "Jademaul", "Rubyfist", "Marblegrip", "Silverpick", "Blackanvil", "Coalhammer", "Deepdelver", "Stonefoot", "Forgeguard", "Hearthfury", "Flamebrow", "Bronzeforge", "Evergrip", "Longshield", "Runeforge", "Bouldershield", "Stoutmantle", "Proudstone", "Rockfury", "Deepaxe", "Thundershield", "Runebrow", "Goldgrip", "Firestone", "Hearthshield", "Anvilstrike", "Steelbeard", "Darkanvil", "Gritstone", "Ironbreaker", "Mithrilbeard", "Copperhand", "Kegfist", "Flintgrip", "Stormpick", "Hardshield", "Frostheart", "Emberfist", "Stoneguard", "Battleborn", "Mountainfury", "Truehammer", "Rockanvil", "Frostbrow", "Thunderheart", "Gritbeard", "Everpeak", "Anvilshield", "Flameforge", "Bouldergrip", "Jadestone", "Amberfist", "Marblestone", "Runeshield", "Darkforge", "Hearthgrip", "Stormgrip", "Oakenheart", "Steelforge", "Coalbraid", "Goldshield", "Firegrip", "Stronghold", "Silverfury", "Brassbeard", "Mithrilhelm", "Hammerfall", "Stoneforge", "Ruggedfist", "Gravelfist", "Deepbrow", "Thunderpick", "Runefist", "Darkbraid", "Rockhelm", "Quakefist", "Ironpeak", "Proudbeard"],
      "ageAdulte": 16,
      "esperanceVieMax": 350,
      "dureeGestationMois": 12,
      "ageApprentissage": 5,
      "ageTravail": 12
    }
  },
  "compatibilites": {
    "Humain": ["Elfe", "Demi-Elfe", "Demi-Orc", "Nain"],
    "Elfe": ["Humain", "Demi-Elfe"],
    "Demi-Elfe": ["Humain", "Elfe"],
    "Orc": ["Demi-Orc"],
    "Demi-Orc": ["Humain", "Orc"],
    "Nain": ["Humain"]
  },
  "racesMixtes": {
    "Humain-Elfe": "Demi-Elfe",
    "Elfe-Humain": "Demi-Elfe",
    "Humain-Orc": "Demi-Orc",
    "Orc-Humain": "Demi-Orc"
  }
};